name: Conformance check

on:
  pull_request:
    branches:
      - main

jobs:
  conform:
    name: Conformance
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Checkout main branch
        run: git fetch --no-tags origin main:main

      - name: Conform action
        uses: talos-systems/conform@v0.1.0-alpha.30
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
